name: CI de Testes Mobile com Appium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  actions: read

env:
  MAVEN_OPTS: "-Dmaven.artifact.threads=8 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Djava.net.preferIPv4Stack=true"

jobs:
  build-and-push-image:
    name: Build & Push da Imagem (GHCR)
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.meta.outputs.image }}
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Definir metadados da imagem
        id: meta
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/mobile-tests"
          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
          echo "tags=${IMAGE}:latest,${IMAGE}:${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

      - name: Build & Push (com cache)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  run-tests:
    name: Executar Testes (na imagem publicada)
    runs-on: ubuntu-latest
    needs: build-and-push-image

    container:
      image: ghcr.io/${{ github.repository_owner }}/mobile-tests:latest
      env:
        MAVEN_OPTS: "-Dmaven.artifact.threads=8 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Djava.net.preferIPv4Stack=true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: /root/.m2
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            m2-${{ runner.os }}-

      - name: Iniciar Appium local (opcional)
        run: |
          nohup appium --base-path /wd/hub > appium.log 2>&1 &
          for i in {1..30}; do
            curl -sf http://localhost:4723/wd/hub/status && break
            sleep 1
          done
          curl -sf http://localhost:4723/wd/hub/status || (echo "Appium não respondeu a tempo" && exit 1)

      - name: Rodar testes (Maven)
        run: |
          mvn -B clean test

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
          retention-days: 7

      - name: Upload appium.log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-log
          path: appium.log
          retention-days: 7