name: CI de Testes Mobile com Appium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-android:
    runs-on: macos-latest
    timeout-minutes: 45

    env:
      APP_PACKAGE: com.saucelabs.mydemoapp.rn
      APP_ACTIVITY: .MainActivity

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Appium + Driver
        run: |
          npm i -g appium@latest
          appium driver install uiautomator2

      - name: Iniciar Emulador, Appium e Rodar Testes
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: arm64-v8a
          profile: pixel_6
          emulator-boot-timeout: 1800
          disable-animations: true
          emulator-options: >-
            -no-window
            -no-snapshot
            -no-boot-anim
            -no-audio
          script: |
            echo "== Esperando o boot do emulador =="
            adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

            echo "== Desbloqueando tela =="
            adb shell input keyevent 82

            echo "== Subindo Appium e aguardando porta 4723 =="
            appium > appium.log 2>&1 &
            npx wait-on tcp:4723 -t 120000

            echo "== Rodando testes Maven =="
            mvn -B clean test

            echo "== Coletando logs para diagnóstico =="
            adb logcat -d > logcat.txt || true

      - name: Allure (resultados)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
          retention-days: 7

      - name: Logs (Appium/Logcat)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-mobile
          path: |
            appium.log
            logcat.txt
          retention-days: 7