name: CI de Testes Mobile com Appium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-appium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Java JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Appium e Driver
        run: |
          # A CORREÇÃO ESTÁ AQUI: Adicionamos o @latest
          npm install -g appium@latest
          appium driver install uiautomator2

      - name: Iniciar Servidor Appium em Background
        run: |
          appium &

      - name: Iniciar Emulador Android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: echo "Emulador iniciado."

      - name: Executar testes com Maven
        run: mvn clean test

      - name: Upload dos Relatórios de Teste (Allure)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
          retention-days: 7